### ISSUE TITLE
Which local broker used by that addon ???

### ISSUE THREAD

**Issue by vincegre** [tschmidty69/hassio-snips#7]
Hi

It is stated in documentation that it uses the MQTT broker avalaible as add-on in hassio but it doesn't look so !! I have setup a broker using the hassio one and it's used by HA and my ESP modules but not by SNIPS still installed by addon in hassio !!
What's that mess ? and how to get snips to use the hassio one instead of its useless internal one ?

Thanks

**Comment by todschmidt** [comment]
The snips addon uses a mosquitto broker within the addon that bridges to the separate mosquitto addon

**Comment by vincegre** [comment]
> The snips addon uses a mosquitto broker within the addon that bridges to the separate mosquitto addon

Thanks for clarification, will check if it's ok for satellite setup as I'm not sure it'll work with a man-in-the-middle system for MQTT :-/

**Comment by todschmidt** [comment]
It will. The bridge is configured to send everything HA gets on MQTT into snips.

**Comment by vincegre** [comment]
> It will. The bridge is configured to send everything HA gets on MQTT into snips.

Thanks it looks to work unless I still have some other issues ;)
